devs = {
    '-audiodev pa,id=audio0 -device ac97,audiodev=audio0': {'type': 'audio'},
    '-device adlib':                                       {'type': 'audio'},
    '-device cs4231a':                                     {'type': 'audio'},
    '-device ES1370':                                      {'type': 'audio'},
    '-device gus':                                         {'type': 'audio'},
    '-device intel-hda -device hda-duplex':                {'type': 'audio'},
    '-device intel-hda -device hda-micro':                 {'type': 'audio'},
    '-device intel-hda -device hda-output':                {'type': 'audio'},
    '-device intel-hda -device ich9-intel-hda':            {'type': 'audio'},
    '-device intel-hda':                                   {'type': 'audio'},
    '-device sb16':                                        {'type': 'audio'},
    '-device usb-audio':                                   {'type': 'audio'},
    '-device virtio-sound-pci':                            {'type': 'audio'},

    '-device ati-vga':                                     {'type': 'gpu'},
    '-device bochs-display':                               {'type': 'gpu'},
    '-device cirrus-vga':                                  {'type': 'gpu'},
    '-device isa-cirrus-vga':                              {'type': 'gpu'},
    '-device isa-vga':                                     {'type': 'gpu'},
    '-device qxl':                                         {'type': 'gpu'},
    '-device qxl-vga':                                     {'type': 'gpu'},
    '-device ramfb':                                       {'type': 'gpu'},
    '-device secondary-vga':                               {'type': 'gpu'},
    '-device VGA':                                         {'type': 'gpu'},
    '-device virtio-vga':                                  {'type': 'gpu'},
    '-device vmware-svga':                                 {'type': 'gpu'},

    '-device usb-kbd':                                     {'type': 'input'},
    '-chardev file,id=braille,path=/dev/urandom -device usb-braille,chardev=braille': {'type': 'input'},
    '-device usb-ccid -device usb-ccid,id=smartcard0': {'type': 'input'},
    '-device usb-mouse':                                   {'type': 'input'},
    '-chardev file,id=parport0,path=/dev/null -device usb-parallel,chardev=parport0': {'type': 'input'},
    '-device usb-tablet':                                  {'type': 'input'},
    '-device i8042':                                       {'type': 'input'},
    '-device tpci200,id=ipack0 -device ipoctal232,bus=ipack0.0': {'type': 'input'},
    '-chardev file,id=parport0,path=/dev/null -device isa-parallel,chardev=parport0': {'type': 'input'},
    '-device isa-serial':                                  {'type': 'input'},
    '-device pci-serial':                                  {'type': 'input'},
    '-device pci-serial-2x':                               {'type': 'input'},
    '-device pci-serial-4x':                               {'type': 'input'},
    '-device tpci200':                                     {'type': 'input'},
    '-device usb-wacom-tablet':                            {'type': 'input'},
    '-device virtio-keyboard-pci':                         {'type': 'input'},
    '-device virtio-mouse-pci':                            {'type': 'input'},
    '-device virtio-multitouch-pci':                       {'type': 'input'},
    '-device virtio-serial-pci':                           {'type': 'input'},
    '-device virtio-serial-pci-non-transitional':          {'type': 'input'},
    '-device virtio-serial-pci-transitional':              {'type': 'input'},
    '-device virtio-tablet-pci':                           {'type': 'input'},
    '-device ich9-usb-ehci1':                              {'type': 'input'},
    '-device ich9-usb-ehci2':                              {'type': 'input'},
    '-device ich9-usb-uhci1':                              {'type': 'input'},
    '-device ich9-usb-uhci2':                              {'type': 'input'},
    '-device ich9-usb-uhci3':                              {'type': 'input'},
    '-device ich9-usb-uhci4':                              {'type': 'input'},
    '-device ich9-usb-uhci5':                              {'type': 'input'},
    '-device ich9-usb-uhci6':                              {'type': 'input'},
    '-device nec-usb-xhci':                                {'type': 'input'},
    '-device pci-ohci':                                    {'type': 'input'},
    '-device piix3-usb-uhci':                              {'type': 'input'},
    '-device piix4-usb-uhci':                              {'type': 'input'},
    '-device qemu-xhci':                                   {'type': 'input'},
    '-device usb-ehci':                                    {'type': 'input'},

    'e1000':                                {'type': 'net'},
    'e1000-82544gc':                        {'type': 'net'},
    'e1000-82545em':                        {'type': 'net'},
    'e1000e':                               {'type': 'net'},
    'i82550':                               {'type': 'net'},
    'i82551':                               {'type': 'net'},
    'i82557a':                              {'type': 'net'},
    'i82557b':                              {'type': 'net'},
    'i82557c':                              {'type': 'net'},
    'i82558a':                              {'type': 'net'},
    'i82558b':                              {'type': 'net'},
    'i82559a':                              {'type': 'net'},
    'i82559b':                              {'type': 'net'},
    'i82559c':                              {'type': 'net'},
    'i82559er':                             {'type': 'net'},
    'i82562':                               {'type': 'net'},
    'i82801':                               {'type': 'net'},
    'ne2k_pci':                             {'type': 'net'},
    'pcnet':                                {'type': 'net'},
    'rtl8139':                              {'type': 'net'},
    'tulip':                                {'type': 'net'},
    'virtio-net-pci':                       {'type': 'net'},
    'virtio-net-pci-non-transitional':      {'type': 'net'},
    'virtio-net-pci-transitional':          {'type': 'net'},
    'vmxnet3':                              {'type': 'net'},

    'am53c974':                             {'type': 'storage'},
    'cxl-type3':                            {'type': 'storage'},
    'dc390':                                {'type': 'storage'},
    'floppy':                               {'type': 'storage'},
    'ich9-ahci':                            {'type': 'storage'},
    'ide-cd':                               {'type': 'storage'},
    'ide-cf':                               {'type': 'storage'},
    'ide-hd':                               {'type': 'storage'},
    'isa-fdc':                              {'type': 'storage'},
    'isa-ide':                              {'type': 'storage'},
    'lsi53c810':                            {'type': 'storage'},
    'lsi53c895a':                           {'type': 'storage'},
    'megasas':                              {'type': 'storage'},
    'megasas-gen2':                         {'type': 'storage'},
    'mptsas1068':                           {'type': 'storage'},
    'nvdimm':                               {'type': 'storage'},
    'nvme,serial':                          {'type': 'storage'},
    'nvme-ns,serial':                       {'type': 'storage'},
    'nvme-subsys,serial':                   {'type': 'storage'},
    'piix3-ide':                            {'type': 'storage'},
    'piix4-ide':                            {'type': 'storage'},
    'pvscsi':                               {'type': 'storage'},
    'scsi-block':                           {'type': 'storage'},
    'scsi-cd':                              {'type': 'storage'},
    'scsi-generic':                         {'type': 'storage'},
    'scsi-hd':                              {'type': 'storage'},
    'sd-card':                              {'type': 'storage'},
    'sd-card-spi':                          {'type': 'storage'},
    'sdhci-pci':                            {'type': 'storage'},
    'ufs':                                  {'type': 'storage'},
    'usb-bot':                              {'type': 'storage'},
    'usb-mtp':                              {'type': 'storage'},
    'usb-storage':                          {'type': 'storage'},
    'usb-uas':                              {'type': 'storage'},
    'vhost-scsi':                           {'type': 'storage'},
    'vhost-scsi-pci':                       {'type': 'storage'},
    'vhost-scsi-pci-non-transitional':      {'type': 'storage'},
    'vhost-scsi-pci-transitional':          {'type': 'storage'},
    'vhost-user-blk':                       {'type': 'storage'},
    'vhost-user-blk-pci':                   {'type': 'storage'},
    'vhost-user-blk-pci-non-transitional':  {'type': 'storage'},
    'vhost-user-blk-pci-transitional':      {'type': 'storage'},
    'vhost-user-fs-device':                 {'type': 'storage'},
    'vhost-user-fs-pci':                    {'type': 'storage'},
    'vhost-user-scsi':                      {'type': 'storage'},
    'vhost-user-scsi-pci':                  {'type': 'storage'},
    'vhost-user-scsi-pci-non-transitional': {'type': 'storage'},
    'vhost-user-scsi-pci-transitional':     {'type': 'storage'},
    'virtio-9p-device':                     {'type': 'storage'},
    'virtio-9p-pci':                        {'type': 'storage'},
    'virtio-9p-pci-non-transitional':       {'type': 'storage'},
    'virtio-9p-pci-transitional':           {'type': 'storage'},
    'virtio-blk-device':                    {'type': 'storage'},
    'virtio-blk-pci':                       {'type': 'storage'},
    'virtio-blk-pci-non-transitional':      {'type': 'storage'},
    'virtio-blk-pci-transitional':          {'type': 'storage'},
    'virtio-pmem':                          {'type': 'storage'},
    'virtio-scsi-device':                   {'type': 'storage'},
    'virtio-scsi-pci':                      {'type': 'storage'},
    'virtio-scsi-pci-non-transitional':     {'type': 'storage'},
    'virtio-scsi-pci-transitional':         {'type': 'storage'}
}